language: node_js
node_js:
  - "8"

before_script:
  - sudo apt-get install python-software-properties
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:rwky/graphicsmagick
  - sudo apt-get update
  - sudo apt-get install graphicsmagick
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build
