language: node_js
node_js:
  - "8"

before_install:
  - sudo apt-get install -y python-software-properties
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:rwky/graphicsmagick
  - sudo apt-get update -y
  - sudo apt-get install -y graphicsmagick

before_script:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build
